obj-$(CONFIG_MACH_K2_CL) += board-k2_cl.o
obj-$(CONFIG_MACH_K2_CL) += board-k2_cl-regulator.o
obj-$(CONFIG_MACH_K2_CL) += board-k2_cl-gpiomux.o
obj-$(CONFIG_MACH_K2_CL) += board-k2_cl-storage.o
obj-$(CONFIG_MACH_K2_CL) += board-k2_cl-mmc.o
obj-$(CONFIG_MACH_K2_CL) += board-k2_cl-rfkill.o
obj-$(CONFIG_MACH_K2_CL) += board-k2_cl-wifi.o
obj-$(CONFIG_MACH_K2_CL) += board-k2-gpu.o
obj-$(CONFIG_MACH_K2_CL) += board-k2_cl-audio.o
obj-$(CONFIG_MACH_K2_CL) += board-k2_cl-pmic.o
obj-$(CONFIG_MACH_K2_CL) += board-k2_cl-keypad.o
ifeq ($(CONFIG_MSM_CAMERA),y)
obj-$(CONFIG_MACH_K2_CL) += board-k2-camera.o
endif
obj-$(CONFIG_MACH_K2_CL) += display/
CFLAGS_board-k2-display.o += -Idrivers/video
